(defun c:TEST ()
  (setq selections_list ( list ))
  (setq i (getint "Digite o número de seleções: "))
  (princ "Clique nas extremidades que enquadram sua seleção: ")
  (repeat i 
    (setq current_selection_first_point ( getpoint ))
    (setq current_selection_second_point ( getpoint ))
    (setq selections_list ( append selections_list ( list current_selection_first_point current_selection_second_point)))
  )
  (if (= (/ i 2) 0)
    (
      (setq objects_inside_selection (ssget "W" (nth 0 selections_list) (nth 1 selections_list)))
      (princ (sslength objects_inside_selection))
    )
    (repeat (/ i 2)
      (setq objects_inside_selection (ssget "W" (nth (- (* i 2) 2) selections_list) (nth (- (* i 2) 1) selections_list)))
      (princ (sslength objects_inside_selection))
    )
  )
)